services:
  windows-ltsc:
    image: dockurr/windows
    container_name: win10-ltsc
    environment:
      VERSION: "10"          # 使用 Windows 10 LTSC 长期服务版（无应用商店/Edge等冗余组件）
      EDITION: "Enterprise"  # 企业版更适合轻量化
      USERNAME: "meegooboo"  # 账户名
      PASSWORD: "meegooboo" # 密码
      RAM_SIZE: "4G"         # 内存减至 8GB（LTSC 最低要求2G）
      CPU_CORES: "2"         # CPU 核心数
      DISK_SIZE: "32G"       # 磁盘精简至 64GB（LTSC 安装后仅需 12GB）
      DISABLE_VIRTIO: "true" # 禁用虚拟驱动（提升老硬件兼容性）
      SKIP_TPM_CHECK: "true" # 绕过 TPM 检查（减少启动项）
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8007:8006"          # 修改 Web 控制台端口避免冲突
      - "3390:3389/tcp"      # 修改 RDP 端口避免冲突
    stop_grace_period: 1m    # 缩短关闭等待时间
    restart: unless-stopped   # 异常时自动重启